import Head from "next/head";
import Link from "next/link";
import Icon from "../components/Icon";
import Layout from "../components/Layout";
import Post from "../components/Post";
import { getAllMarkdownFilesInDir, MarkdownFile } from "../lib/markdown";

const Home = ({
  posts,
  snippets,
}: {
  posts: MarkdownFile[];
  snippets: MarkdownFile[];
}): JSX.Element => (
  <div>
    <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <section className="text-3xl mb-separator">
        <h1 className="text-4xl font-bold mb-4">Hi, I&rsquo;m Victor</h1>
        <p className="text-base mb-4">
          I&rsquo;m a frontend developer and design enthusiast interested in
          user <br></br>
          experience, software architecture and design systems.
        </p>
        <div className="flex gap-2">
          <Icon icon="github.svg" />
          <Icon icon="email.svg" />
        </div>
      </section>
      <section className="mb-separator">
        <h2 className="text-3xl font-semibold mb-8">Recent posts</h2>
        <section className="flex flex-col gap-14">
          {posts?.map((post: any) => {
            const { slug, frontmatter } = post;
            const { title, description, date } = frontmatter;

            return (
              <Post
                key={title}
                title={title}
                description={description}
                date={date}
                slug={slug}
              />
            );
          })}
        </section>
      </section>
      <section className="mb-separator font-bold">
        <>
          <h2 className="text-3xl mb-4">Latest snippets</h2>
          <ul>
            {snippets?.map((snippet: any, index) => {
              const { slug, frontmatter } = snippet;
              const { title } = frontmatter;
              return (
                <li key={index} className="pt-2 pb-2">
                  <Link href={`snippets/${slug}`}>
                    <a>
                      <span className="flex gap-2 items-center text-lg cursor-pointer">
                        {title} <Icon icon="arrow.svg" />
                      </span>
                    </a>
                  </Link>
                </li>
              );
            })}
          </ul>
        </>
      </section>
    </Layout>
  </div>
);

export async function getStaticProps() {
  // Get the 3 latest posts
  const posts = getAllMarkdownFilesInDir("content/posts").slice(0, 2);
  const snippets = getAllMarkdownFilesInDir("content/snippets").slice(0, 5);

  return {
    props: { posts, snippets },
  };
}

export default Home;
